<?php

namespace App\Http\Resources\Furniture;

use Illuminate\Http\Resources\Json\JsonResource;

class FurnitureResource extends JsonResource
{
    public function toArray($request): array|\JsonSerializable|\Illuminate\Contracts\Support\Arrayable
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}